name: BellLands
version: '1.26.1.2'
main: pl.bell.lands.BellLands
api-version: '1.21'
commands:
  tpa:
    description: Prosba o teleportacje
  tpaccept:
    description: Akceptacja teleportacji
  tpdeny:
    description: Odrzucenie teleportacji
  claim:
    description: Zaimuj teren na ktorym stoisz