name: BellLands
version: '1.26.1.2'
main: pl.bell.lands.BellLands
api-version: '1.21'
commands:
  tpa:
    description: Wysyla prosbe o teleportacje do gracza
    usage: /tpa <gracz>
  tpaccept:
    description: Akceptuje prosbe o teleportacje
  tpdeny:
    description: Odrzuca prosbe o teleportacje